"""empty message

Revision ID: 570d4cf04ce9
Revises: cfa3d8711a7d
Create Date: 2017-08-02 17:49:13.279915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570d4cf04ce9'
down_revision = 'cfa3d8711a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendas_uuid'), 'agendas', ['uuid'], unique=True)
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['agenda'], ['agendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points')
    op.drop_index(op.f('ix_agendas_uuid'), table_name='agendas')
    op.drop_table('agendas')
    # ### end Alembic commands ###
