"""empty message

Revision ID: 5f84a0720dd2
Revises: 0fc627685fed
Create Date: 2017-08-31 20:53:01.048470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f84a0720dd2'
down_revision = '0fc627685fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('timer', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'timer')
    # ### end Alembic commands ###
