"""empty message

Revision ID: 71b441b498c0
Revises: 9b9958a36e03
Create Date: 2017-09-25 18:34:44.083238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b441b498c0'
down_revision = '9b9958a36e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('internal_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'internal_order')
    # ### end Alembic commands ###
