"""empty message

Revision ID: 9b9958a36e03
Revises: 5f84a0720dd2
Create Date: 2017-09-01 17:50:58.783524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9958a36e03'
down_revision = '5f84a0720dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('hours', sa.Integer(), nullable=True))
    op.add_column('points', sa.Column('minutes', sa.Integer(), nullable=True))
    op.add_column('points', sa.Column('seconds', sa.Integer(), nullable=True))
    op.drop_column('points', 'timer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('timer', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('points', 'seconds')
    op.drop_column('points', 'minutes')
    op.drop_column('points', 'hours')
    # ### end Alembic commands ###
