"""empty message

Revision ID: ce29c15a92e9
Revises: 63fa57439402
Create Date: 2017-08-02 15:31:23.619470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce29c15a92e9'
down_revision = '63fa57439402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendas', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agendas', 'users', ['created_by'], ['id'])
    op.add_column('points', sa.Column('agenda', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'points', 'agendas', ['agenda'], ['id'])
    op.drop_column('points', 'agenda_id')
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.add_column('points', sa.Column('agenda_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'points', type_='foreignkey')
    op.drop_column('points', 'agenda')
    op.drop_constraint(None, 'agendas', type_='foreignkey')
    op.drop_column('agendas', 'created_by')
    # ### end Alembic commands ###
