"""empty message

Revision ID: cfa3d8711a7d
Revises: ce29c15a92e9
Create Date: 2017-08-02 16:27:00.467651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa3d8711a7d'
down_revision = 'ce29c15a92e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendas', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendas', 'date_created')
    # ### end Alembic commands ###
