"""empty message

Revision ID: ebe4c4a892ca
Revises: 4ebdd019c8e1
Create Date: 2017-08-03 15:52:04.703327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe4c4a892ca'
down_revision = '4ebdd019c8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('current_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'current_active')
    # ### end Alembic commands ###
